# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180218_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fullname',
            field=models.CharField(default='John Miller', max_length=255),
        ),
    ]
