# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_remove_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping address')], default='shipping', max_length=50),
        ),
    ]
