# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping address'), ('billing', 'Billing address')], max_length=50),
        ),
    ]
