# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20180322_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
