# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20180328_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
