# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20180328_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, default=400003, max_digits=6),
        ),
    ]
