# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0011_auto_20180328_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='400003', max_length=6),
        ),
    ]
