# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='mobile_number',
            field=models.CharField(default='9999999999', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
