# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default=9999999999),
        ),
    ]
