# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180223_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='John Miller', max_length=255, null=True),
        ),
    ]
