# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180309_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestemail',
            name='active',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='updated',
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
