# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180309_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guestemail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestemail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
