# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180309_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='guestemail',
            name='last_name',
            field=models.CharField(default='Miller', max_length=255),
        ),
        migrations.AddField(
            model_name='guestemail',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9999999999', max_length=128),
        ),
    ]
