# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180312_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestEmail',
            new_name='GuestDetails',
        ),
    ]
