# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('author', models.CharField(default='Author', max_length=20)),
                ('short_description', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('slug', models.SlugField()),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
