# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180314_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
