# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_delete_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
