# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180315_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
