# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
