# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='response',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
