# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180325_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, default='1234567', max_length=50, null=True),
        ),
    ]
