# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('author', models.CharField(default='Author', max_length=100)),
                ('short_description', models.CharField(default='A Short Description Of the Book', max_length=100)),
                ('category', models.CharField(choices=[('cfa', 'CFA'), ('frm', 'FRM'), ('erp', 'ERP'), ('caia', 'CAIA'), ('others', 'Others'), ('free', 'Free')], default='others', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('display_price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('in_stock', models.BooleanField(default=True)),
                ('specs_line_1', models.CharField(blank=True, default='Line 1', max_length=150, null=True)),
                ('specs_line_2', models.CharField(blank=True, default='Line 2', max_length=150, null=True)),
                ('specs_line_3', models.CharField(blank=True, default='Line 3', max_length=150, null=True)),
                ('specs_line_4', models.CharField(blank=True, default='Line 4', max_length=150, null=True)),
                ('specs_line_5', models.CharField(blank=True, default='Line 5', max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
