# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180207_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
