# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Author', max_length=20),
        ),
    ]
