# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
