# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_percent_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cfa', 'CFA'), ('frm', 'FRM'), ('erp', 'ERP'), ('caia', 'CAIA'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
