# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
