# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180302_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cfa', 'CFA'), ('frm', 'FRM'), ('erp', 'ERP'), ('caia', 'CAIA'), ('others', 'Others'), ('free', 'Free')], default='others', max_length=10),
        ),
    ]
