# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180311_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
