# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180314_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='A Short Description Of the Book', max_length=50),
        ),
    ]
