# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20180314_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='Author', max_length=50),
        ),
    ]
